version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env.local
    environment:
      - REDIS_DOMAIN=redis
      - MONGO_DOMAIN=mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 60000
    ports:
      - "60000:60000"

  redis:
    depends_on:
      - mongo
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]